// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcU3Yk5mYYooLCQJP2060ssxZNxddN9aA',
    appId: '1:716972217713:web:93aebdec5b1fce719792d0',
    messagingSenderId: '716972217713',
    projectId: 'brain-tumor-detector1685',
    authDomain: 'brain-tumor-detector1685.firebaseapp.com',
    databaseURL: 'https://brain-tumor-detector1685-default-rtdb.firebaseio.com',
    storageBucket: 'brain-tumor-detector1685.appspot.com',
    measurementId: 'G-FBE9T5C3Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-uGk1KSh1uDA-hws-8m7xNjH8AsLAE7w',
    appId: '1:716972217713:android:11299775d01ef7609792d0',
    messagingSenderId: '716972217713',
    projectId: 'brain-tumor-detector1685',
    databaseURL: 'https://brain-tumor-detector1685-default-rtdb.firebaseio.com',
    storageBucket: 'brain-tumor-detector1685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTldJGC3fvhK36QfQ1uC5VV-U9SlhNLpc',
    appId: '1:716972217713:ios:346142da22072a6a9792d0',
    messagingSenderId: '716972217713',
    projectId: 'brain-tumor-detector1685',
    databaseURL: 'https://brain-tumor-detector1685-default-rtdb.firebaseio.com',
    storageBucket: 'brain-tumor-detector1685.appspot.com',
    iosClientId: '716972217713-469uj0eneeet8hounqoqpar3ap9cnc1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainTumorDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTldJGC3fvhK36QfQ1uC5VV-U9SlhNLpc',
    appId: '1:716972217713:ios:9d6f313e04fc9eb59792d0',
    messagingSenderId: '716972217713',
    projectId: 'brain-tumor-detector1685',
    databaseURL: 'https://brain-tumor-detector1685-default-rtdb.firebaseio.com',
    storageBucket: 'brain-tumor-detector1685.appspot.com',
    iosClientId: '716972217713-2s68205drgrc53sa8gt288rg0qatr0iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainTumorDetector.RunnerTests',
  );
}
